### ISSUE TITLE
Map -Search Feature

### ISSUE THREAD

**Issue by 0n11san** [0n11san/fyrr_v6#8]

**Comment by antoinebartholomew** [comment]
https://stackoverflow.com/questions/39939322/difficulty-importing-searchbox-from-react-google-maps

**Comment by antoinebartholomew** [comment]
https://github.com/google-map-react/google-map-react/issues/30

**Comment by antoinebartholomew** [comment]
https://stackoverflow.com/questions/39939322/difficulty-importing-searchbox-from-react-google-maps
